package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Goods;
import greendao.GoodsUrls;
import greendao.GoodsPrices;

import greendao.GoodsDao;
import greendao.GoodsUrlsDao;
import greendao.GoodsPricesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsDaoConfig;
    private final DaoConfig goodsUrlsDaoConfig;
    private final DaoConfig goodsPricesDaoConfig;

    private final GoodsDao goodsDao;
    private final GoodsUrlsDao goodsUrlsDao;
    private final GoodsPricesDao goodsPricesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsDaoConfig = daoConfigMap.get(GoodsDao.class).clone();
        goodsDaoConfig.initIdentityScope(type);

        goodsUrlsDaoConfig = daoConfigMap.get(GoodsUrlsDao.class).clone();
        goodsUrlsDaoConfig.initIdentityScope(type);

        goodsPricesDaoConfig = daoConfigMap.get(GoodsPricesDao.class).clone();
        goodsPricesDaoConfig.initIdentityScope(type);

        goodsDao = new GoodsDao(goodsDaoConfig, this);
        goodsUrlsDao = new GoodsUrlsDao(goodsUrlsDaoConfig, this);
        goodsPricesDao = new GoodsPricesDao(goodsPricesDaoConfig, this);

        registerDao(Goods.class, goodsDao);
        registerDao(GoodsUrls.class, goodsUrlsDao);
        registerDao(GoodsPrices.class, goodsPricesDao);
    }
    
    public void clear() {
        goodsDaoConfig.getIdentityScope().clear();
        goodsUrlsDaoConfig.getIdentityScope().clear();
        goodsPricesDaoConfig.getIdentityScope().clear();
    }

    public GoodsDao getGoodsDao() {
        return goodsDao;
    }

    public GoodsUrlsDao getGoodsUrlsDao() {
        return goodsUrlsDao;
    }

    public GoodsPricesDao getGoodsPricesDao() {
        return goodsPricesDao;
    }

}
