package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GOODS".
 */
public class Goods {

    private Long id;
    private String type;
    private String brand;
    private String name;
    private String standard;
    private Double cheapestOnline;
    private Double cheapestOffline;

    public Goods() {
    }

    public Goods(Long id) {
        this.id = id;
    }

    public Goods(Long id, String type, String brand, String name, String standard, Double cheapestOnline, Double cheapestOffline) {
        this.id = id;
        this.type = type;
        this.brand = brand;
        this.name = name;
        this.standard = standard;
        this.cheapestOnline = cheapestOnline;
        this.cheapestOffline = cheapestOffline;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStandard() {
        return standard;
    }

    public void setStandard(String standard) {
        this.standard = standard;
    }

    public Double getCheapestOnline() {
        return cheapestOnline;
    }

    public void setCheapestOnline(Double cheapestOnline) {
        this.cheapestOnline = cheapestOnline;
    }

    public Double getCheapestOffline() {
        return cheapestOffline;
    }

    public void setCheapestOffline(Double cheapestOffline) {
        this.cheapestOffline = cheapestOffline;
    }

}
