package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GOODS_PRICES".
 */
public class GoodsPrices {

    private Long id;
    private Long goodsId;
    private Long typeId;
    private java.util.Date date;
    private String seller;
    private Double price;
    private String url;

    public GoodsPrices() {
    }

    public GoodsPrices(Long id) {
        this.id = id;
    }

    public GoodsPrices(Long id, Long goodsId, Long typeId, java.util.Date date, String seller, Double price, String url) {
        this.id = id;
        this.goodsId = goodsId;
        this.typeId = typeId;
        this.date = date;
        this.seller = seller;
        this.price = price;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    public Long getTypeId() {
        return typeId;
    }

    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getSeller() {
        return seller;
    }

    public void setSeller(String seller) {
        this.seller = seller;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
