package greendao;

import greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GOODS_PRICES".
 */
public class GoodsPrices {

    private Long goodsPriceId;
    private java.util.Date addDate;
    private String seller;
    private Double price;
    private String urlAddress;
    private Long priceTypeId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient GoodsPricesDao myDao;

    private PriceType priceType;
    private Long priceType__resolvedKey;


    public GoodsPrices() {
    }

    public GoodsPrices(Long goodsPriceId) {
        this.goodsPriceId = goodsPriceId;
    }

    public GoodsPrices(Long goodsPriceId, java.util.Date addDate, String seller, Double price, String urlAddress, Long priceTypeId) {
        this.goodsPriceId = goodsPriceId;
        this.addDate = addDate;
        this.seller = seller;
        this.price = price;
        this.urlAddress = urlAddress;
        this.priceTypeId = priceTypeId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getGoodsPricesDao() : null;
    }

    public Long getGoodsPriceId() {
        return goodsPriceId;
    }

    public void setGoodsPriceId(Long goodsPriceId) {
        this.goodsPriceId = goodsPriceId;
    }

    public java.util.Date getAddDate() {
        return addDate;
    }

    public void setAddDate(java.util.Date addDate) {
        this.addDate = addDate;
    }

    public String getSeller() {
        return seller;
    }

    public void setSeller(String seller) {
        this.seller = seller;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getUrlAddress() {
        return urlAddress;
    }

    public void setUrlAddress(String urlAddress) {
        this.urlAddress = urlAddress;
    }

    public Long getPriceTypeId() {
        return priceTypeId;
    }

    public void setPriceTypeId(Long priceTypeId) {
        this.priceTypeId = priceTypeId;
    }

    /** To-one relationship, resolved on first access. */
    public PriceType getPriceType() {
        Long __key = this.priceTypeId;
        if (priceType__resolvedKey == null || !priceType__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PriceTypeDao targetDao = daoSession.getPriceTypeDao();
            PriceType priceTypeNew = targetDao.load(__key);
            synchronized (this) {
                priceType = priceTypeNew;
            	priceType__resolvedKey = __key;
            }
        }
        return priceType;
    }

    public void setPriceType(PriceType priceType) {
        synchronized (this) {
            this.priceType = priceType;
            priceTypeId = priceType == null ? null : priceType.getPriceTypeId();
            priceType__resolvedKey = priceTypeId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
