package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GOODS_URLS".
 */
public class GoodsUrls {

    private Long id;
    private Long goodsId;
    private String url;

    public GoodsUrls() {
    }

    public GoodsUrls(Long id) {
        this.id = id;
    }

    public GoodsUrls(Long id, Long goodsId, String url) {
        this.id = id;
        this.goodsId = goodsId;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
