package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.GoodsType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GOODS_TYPE".
*/
public class GoodsTypeDao extends AbstractDao<GoodsType, Long> {

    public static final String TABLENAME = "GOODS_TYPE";

    /**
     * Properties of entity GoodsType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property GoodsTypeId = new Property(0, Long.class, "goodsTypeId", true, "GOODS_TYPE_ID");
        public final static Property GoodsTypeName = new Property(1, String.class, "goodsTypeName", false, "GOODS_TYPE_NAME");
    };

    private DaoSession daoSession;


    public GoodsTypeDao(DaoConfig config) {
        super(config);
    }
    
    public GoodsTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GOODS_TYPE\" (" + //
                "\"GOODS_TYPE_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: goodsTypeId
                "\"GOODS_TYPE_NAME\" TEXT);"); // 1: goodsTypeName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GOODS_TYPE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GoodsType entity) {
        stmt.clearBindings();
 
        Long goodsTypeId = entity.getGoodsTypeId();
        if (goodsTypeId != null) {
            stmt.bindLong(1, goodsTypeId);
        }
 
        String goodsTypeName = entity.getGoodsTypeName();
        if (goodsTypeName != null) {
            stmt.bindString(2, goodsTypeName);
        }
    }

    @Override
    protected void attachEntity(GoodsType entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GoodsType readEntity(Cursor cursor, int offset) {
        GoodsType entity = new GoodsType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // goodsTypeId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // goodsTypeName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GoodsType entity, int offset) {
        entity.setGoodsTypeId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGoodsTypeName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GoodsType entity, long rowId) {
        entity.setGoodsTypeId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GoodsType entity) {
        if(entity != null) {
            return entity.getGoodsTypeId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
