package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GOODS_URLS".
 */
public class GoodsUrls {

    private Long goodsUrlId;
    private String urlAddress;

    public GoodsUrls() {
    }

    public GoodsUrls(Long goodsUrlId) {
        this.goodsUrlId = goodsUrlId;
    }

    public GoodsUrls(Long goodsUrlId, String urlAddress) {
        this.goodsUrlId = goodsUrlId;
        this.urlAddress = urlAddress;
    }

    public Long getGoodsUrlId() {
        return goodsUrlId;
    }

    public void setGoodsUrlId(Long goodsUrlId) {
        this.goodsUrlId = goodsUrlId;
    }

    public String getUrlAddress() {
        return urlAddress;
    }

    public void setUrlAddress(String urlAddress) {
        this.urlAddress = urlAddress;
    }

}
