package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GOODS_PRICE".
 */
public class goods_price {

    private Long id;
    private Double price;
    private java.util.Date date;

    public goods_price() {
    }

    public goods_price(Long id) {
        this.id = id;
    }

    public goods_price(Long id, Double price, java.util.Date date) {
        this.id = id;
        this.price = price;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
