package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.PriceType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRICE_TYPE".
*/
public class PriceTypeDao extends AbstractDao<PriceType, Long> {

    public static final String TABLENAME = "PRICE_TYPE";

    /**
     * Properties of entity PriceType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PriceTypeId = new Property(0, Long.class, "priceTypeId", true, "PRICE_TYPE_ID");
        public final static Property PriceTypeName = new Property(1, String.class, "priceTypeName", false, "PRICE_TYPE_NAME");
    };


    public PriceTypeDao(DaoConfig config) {
        super(config);
    }
    
    public PriceTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRICE_TYPE\" (" + //
                "\"PRICE_TYPE_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: priceTypeId
                "\"PRICE_TYPE_NAME\" TEXT);"); // 1: priceTypeName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRICE_TYPE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PriceType entity) {
        stmt.clearBindings();
 
        Long priceTypeId = entity.getPriceTypeId();
        if (priceTypeId != null) {
            stmt.bindLong(1, priceTypeId);
        }
 
        String priceTypeName = entity.getPriceTypeName();
        if (priceTypeName != null) {
            stmt.bindString(2, priceTypeName);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PriceType readEntity(Cursor cursor, int offset) {
        PriceType entity = new PriceType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // priceTypeId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // priceTypeName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PriceType entity, int offset) {
        entity.setPriceTypeId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPriceTypeName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PriceType entity, long rowId) {
        entity.setPriceTypeId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PriceType entity) {
        if(entity != null) {
            return entity.getPriceTypeId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
